### PR TITLE
added gibbs and phase diagrams

### PR DESCRIPTION
**Pull request by LoganESmith0**

### CODE REVIEW

**Review by cadalyjr — APPROVED** [review]
I suggest you add an image of a phase diagram

**Review by marie-nikolov — APPROVED** [review]
Looks grand champ!

**Review by rgoudy2 — APPROVED** [review]
Reviewed, will need to handle merge conflicts

**Review by kstreu — APPROVED** [review]
Nice additions, just writing a note that we have a typo in line 19 to fix. (I don't think it's necessary to fix before approving these changes)

**Pull request merged**
