### PR TITLE
Math Section - Added Differentiation techniques and simple derivative explanation

### PR DESCRIPTION
**Pull request by Sil-Ethan**
Inclusions (all involving math.md):

- Added a simple explanation of derivative/differentiation. Needs to be rewritten, but the main idea is that derivative = **SLOPE**
- Added various Differentiation techniques such as the chain rule, product rule, etc. 
- Added two images for functions within math.md
- Started section on getting an understanding of critical points, first derivatives, second derivatives, etc. I will not be explaining derivatives above second derivatives until the series section. 
- Strikethrough a section about the formal definition of a derivative. I may or may not include that definition. 

Not sure if I will delete the branch, but I probably will and start a new branch called "math-derivative_analysis-ethan"

### CODE REVIEW

**Review by LoganESmith0 — COMMENTED** [review]
product rule typo

**Review by marie-nikolov — COMMENTED** [review]
Everything looks good except this part: 

 - Second Derivatives and Beyond 
  - Critical Points
  - Inexact and Exact Differentials
    - Exact differential follows the Fundamental Theorem of Calculus s.t. 
$\frac{\partial f(x)}{\partial x} = f'(x)$
the last line I do not think is showing up in markdown format

**Review by LoganESmith0 — COMMENTED** [review]
quotient rule typo

**Review by LoganESmith0 — APPROVED** [review]
Looks good 
 👍

**Pull request merged**
