### PR TITLE
removed fake matrix, added ideal gas sentence

### PR DESCRIPTION
**Pull request by thaupt5542**
Testing

### CODE REVIEW

**Review by Samgonza — APPROVED** [review]
reviewed :)

**Review by Sil-Ethan — CHANGES_REQUESTED** [review]
I think the problem is that the backslashes are not correct. Was this fake matrix just a test, so it is not really needed? Can you mess with the matrix more?

**Review by thaupt5542 — COMMENTED** [review]
Matrix was just a test

**Review by Sil-Ethan — APPROVED** [review]
Accepted deletion of test matrix

**Pull request merged**
